name: Update Requirements in README

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write  # Allow commit changes

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipreqs

      - name: Generate requirements.txt
        run: |
          # Generate the requirements.txt file using pipreqs
          pipreqs . --force

      - name: Update README.md
        run: |
          # Extract the required libraries and format them into a pip install command
          pip freeze > requirements.txt
          # Replace the # Requirements section in README.md with the pip install command
          sed -i "/# Requirements/,+1d" README.md
          echo -e "\n# Requirements\n\n\`\`\`bash\npip install -r requirements.txt\n\`\`\`" >> README.md

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md requirements.txt
          git commit -m "Update Requirements section in README"
          git push
