name: Update Python Requirements

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pipreqs and safety
        run: |
          python -m pip install --upgrade pip
          pip install pipreqs safety

      - name: Generate requirements.txt
        run: |
          # Remove old requirements if exists
          rm -f requirements.txt
          # Generate fresh requirements from code analysis
          pipreqs . --force --mode compat
          # Install generated requirements
          pip install -r requirements.txt
          # Add any missing dependencies
          pip install numpy matplotlib tk customtkinter
          # Freeze all installed packages
          pip freeze > requirements.txt

      - name: Update README.md
        run: |
          # Update Requirements section
          sed -i '/# Requirements/,/```/d' README.md || true
          echo -e "\n# Requirements\n\n\`\`\`bash\npip install -r requirements.txt\n\`\`\`" >> README.md

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add requirements.txt README.md
          git commit -m "Update Python requirements" || true
          git push
